// <auto-generated />
namespace D05_EF6_Migrations_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class _02_Livro_NovoCampoTipo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_02_Livro_NovoCampoTipo));
        
        string IMigrationMetadata.Id
        {
            get { return "202111281744388_02_Livro_NovoCampoTipo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
